name: Build and Test

on:
  pull_request:
    branches:
      - madpro.neocities.org
  push:
    branches:
      - madpro.neocities.org

jobs:
  build-and-test:
    #if: ${{ github.repository == 'madprogramer/quartz-to-neocities' }}
    #strategy:
    #  matrix:
    #    os: [windows-latest, macos-latest, ubuntu-latest]
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - name: Pretier
        run: npm run format

      - name: Check types and style
        run: npm run check

      - name: Test
        run: npm test

      - name: Ensure Quartz builds, check bundle info
        run: npx quartz build --bundleInfo

      #- name: Debug Quartz-generated files
      #  run: |
      #   cd public
      #   ls
      #   cd ..

      # Step 2: Make to update custom homepage + move any files from /sites
      - run: make

      # Step 3: Push to Neocities
      - if: ${{ success() && github.ref == 'refs/heads/main' }}
        id: deploy
        continue-on-error: true
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          dist_dir: public #Have to do it this way because .template is unrecognized
          cleanup: true

      # Step 3 B: Try the Fallback
      - name: Deploy to Neocities fallback
        if: ${{ steps.deploy.outcome == 'failure' && github.ref == 'refs/heads/main' }}
        uses: jonchang/deploy-neocities@master
        with:
          key: ${{ secrets.NEOCITIES_API_KEY }}
          dir: public
          clean: true

      - name: Debug Quartz-generated files
        run: |
          cd public
          ls
          cd ..

